name: nytimes_news_project
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider:

  # Network
  dio: ^5.2.1+1
  pretty_dio_logger: ^1.3.1

  # Serializable
  json_serializable:

  # Tool
  intl:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
